websites = {
    "youtube": "https://www.youtube.com",
    "yt": "https://www.youtube.com",
    "facebook": "https://www.facebook.com",
    "fb": "https://www.facebook.com",
    "github": "https://www.github.com",
    "youtube studio": "https://studio.youtube.com",
    "twitter": "https://www.twitter.com",
    "x": "https://www.twitter.com",
    "instagram": "https://www.instagram.com",
    "insta": "https://www.instagram.com",
    "ig": "https://www.instagram.com",
    "linkedin": "https://www.linkedin.com",
    "wikipedia": "https://www.wikipedia.org",
    "wiki": "https://www.wikipedia.org",
    "reddit": "https://www.reddit.com",
    "pinterest": "https://www.pinterest.com",
    "quora": "https://www.quora.com",
    "tumblr": "https://www.tumblr.com",
    "flickr": "https://www.flickr.com",
    "snapchat": "https://www.snapchat.com",
    "tiktok": "https://www.tiktok.com",
    "vimeo": "https://www.vimeo.com",
    "dropbox": "https://www.dropbox.com",
    "onedrive": "https://www.onedrive.com",
    "google drive": "https://drive.google.com",
    "icloud": "https://www.icloud.com",
    "amazon": "https://www.amazon.com",
    "ebay": "https://www.ebay.com",
    "alibaba": "https://www.alibaba.com",
    "netflix": "https://www.netflix.com",
    "hulu": "https://www.hulu.com",
    "disney plus": "https://www.disneyplus.com",
    "hbo max": "https://www.hbomax.com",
    "spotify": "https://www.spotify.com",
    "soundcloud": "https://www.soundcloud.com",
    "apple music": "https://www.apple.com/apple-music",
    "pandora": "https://www.pandora.com",
    "deezer": "https://www.deezer.com",
    "bandcamp": "https://www.bandcamp.com",
    "bbc": "https://www.bbc.com",
    "cnn": "https://www.cnn.com",
    "nytimes": "https://www.nytimes.com",
    "the guardian": "https://www.theguardian.com",
    "forbes": "https://www.forbes.com",
    "bloomberg": "https://www.bloomberg.com",
    "reuters": "https://www.reuters.com",
    "espn": "https://www.espn.com",
    "fox news": "https://www.foxnews.com",
    "nbc news": "https://www.nbcnews.com",
    "cbs news": "https://www.cbsnews.com",
    "abc news": "https://www.abcnews.go.com",
    "msnbc": "https://www.msnbc.com",
    "npr": "https://www.npr.org",
    "wsj": "https://www.wsj.com",
    "yahoo news": "https://news.yahoo.com",
    "buzzfeed": "https://www.buzzfeed.com",
    "huffpost": "https://www.huffpost.com",
    "canva": "https://www.canva.com",
    "chatgpt": "https://chat.openai.com",
    "slack": "https://www.slack.com",
    "trello": "https://www.trello.com",
    "asana": "https://www.asana.com",
    "zoom": "https://www.zoom.us",
    "skype": "https://www.skype.com",
    "microsoft teams": "https://www.microsoft.com/microsoft-teams",
    "google meet": "https://meet.google.com",
    "webex": "https://www.webex.com",
    "jira": "https://www.atlassian.com/software/jira",
    "notion": "https://www.notion.so",
    "airtable": "https://www.airtable.com",
    "monday": "https://www.monday.com",
    "clickup": "https://www.clickup.com",
    "dropbox paper": "https://www.dropbox.com/paper",
    "confluence": "https://www.atlassian.com/software/confluence",
    "figma": "https://www.figma.com",
    "adobe xd": "https://www.adobe.com/products/xd.html",
    "invision": "https://www.invisionapp.com",
    "microsoft word": "https://www.microsoft.com/microsoft-365/word",
    "google docs": "https://docs.google.com",
    "medium": "https://www.medium.com",
    "wordpress": "https://www.wordpress.com",
    "wix": "https://www.wix.com",
    "squarespace": "https://www.squarespace.com",
    "shopify": "https://www.shopify.com",
    "bigcommerce": "https://www.bigcommerce.com",
    "weebly": "https://www.weebly.com",
    "godaddy": "https://www.godaddy.com",
    "namecheap": "https://www.namecheap.com",
    "bluehost": "https://www.bluehost.com",
    "siteground": "https://www.siteground.com",
    "hostgator": "https://www.hostgator.com",
    "dreamhost": "https://www.dreamhost.com",
    "a2 hosting": "https://www.a2hosting.com",
    "inmotion hosting": "https://www.inmotionhosting.com",
    "digitalocean": "https://www.digitalocean.com",
    "linode": "https://www.linode.com",
    "aws": "https://aws.amazon.com",
    "azure": "https://azure.microsoft.com",
    "google cloud": "https://cloud.google.com",
    "heroku": "https://www.heroku.com",
    "gitlab": "https://www.gitlab.com",
    "bitbucket": "bitbucket.org",
    "codepen": "codepen.io",
    "jsfiddle": "jsfiddle.net",
    "repl.it": "repl.it",
    "stack overflow": "stackoverflow.com",
    "stackoverflow careers": "stackoverflow.com/jobs",
    "glassdoor": "https://www.glassdoor.com",
    "indeed": "https://www.indeed.com",
    "linkedin jobs": "https://www.linkedin.com/jobs",
    "monster": "https://www.monster.com",
    "simplyhired": "https://www.simplyhired.com",
    "angel.co": "angel.co",
    "github jobs": "https://jobs.github.com",
    "ziprecruiter": "https://www.ziprecruiter.com",
    "careerbuilder": "https://www.careerbuilder.com",
    "snagajob": "https://www.snagajob.com",
    "dice": "https://www.dice.com",
    "jobs": "https://www.jobs.com",
    "bamboohr": "https://www.bamboohr.com",
    "workday": "https://www.workday.com",
    "adp": "https://www.adp.com",
    "sap successfactors": "https://www.sap.com/products/hcm.html",
    "oracle hcm": "https://www.oracle.com/applications/human-capital-management",
    "zenefits": "https://www.zenefits.com",
    "paycor": "https://www.paycor.com",
    "paycom": "https://www.paycom.com",
    "gusto": "https://www.gusto.com",
    "square": "squareup.com",
    "stripe": "https://www.stripe.com",
    "paypal": "https://www.paypal.com",
    "venmo": "https://www.venmo.com",
    "cash app": "cash.app",
    "robinhood": "https://www.robinhood.com",
    "etrade": "https://www.etrade.com",
    "fidelity": "https://www.fidelity.com",
    "charles schwab": "https://www.schwab.com",
    "vanguard": "https://investor.vanguard.com",
    "td ameritrade": "https://www.tdameritrade.com",
    "coinbase": "https://www.coinbase.com",
    "binance": "https://www.binance.com",
    "kraken": "https://www.kraken.com",
    "blockchain": "https://www.blockchain.com",
    "gemini": "https://www.gemini.com",
    "bitfinex": "https://www.bitfinex.com",
    "bitstamp": "https://www.bitstamp.net",
    "bittrex": "https://www.bittrex.com",
    "okex": "https://www.okex.com",
    "poloniex": "https://www.poloniex.com",
    "coindesk": "https://www.coindesk.com",
    "cointelegraph": "https://www.cointelegraph.com",
    "decrypt": "https://www.decrypt.co",
    "cryptoslate": "https://www.cryptoslate.com",
    "cryptonews": "https://www.cryptonews.com",
    "coinmarketcap": "https://www.coinmarketcap.com",
    "coingecko": "https://www.coingecko.com",
    "messari": "https://www.messari.io",
    "icodrops": "https://www.icodrops.com",
    "tokenmarket": "https://www.tokenmarket.net",
    "coinpaprika": "https://www.coinpaprika.com",
    "cryptocompare": "https://www.cryptocompare.com",
    "coincheckup": "https://www.coincheckup.com",
    "cryptobriefing": "https://www.cryptobriefing.com",
    "blockonomi": "https://www.blockonomi.com",
    "coininsider": "https://www.coininsider.com",
    "newsbtc": "https://www.newsbtc.com",
    "bitcoin.com": "https://www.bitcoin.com",
    "ethereum.org": "https://www.ethereum.org",
    "litecoin.com": "https://www.litecoin.com",
    "ripple.com": "https://www.ripple.com",
    "cardano.org": "https://www.cardano.org",
    "stellarlumens.com": "https://www.stellarlumens.com",
    "tezos.com": "https://www.tezos.com",
    "eos.io": "https://www.eos.io",
    "neo.org": "https://www.neo.org",
    "iota.org": "https://www.iota.org",
    "monero.org": "https://www.monero.org",
    "zcash.org": "https://www.zcash.org",
    "dash.org": "https://www.dash.org",
    "dogecoin.com": "https://www.dogecoin.com",
    "gpt": "www.chatgpt.com/",
    "whatsapp": "https://web.whatsapp.com",
    "whatsapp web": "https://web.whatsapp.com"
}
